const frame=document.getElementById('inspection-frame'),lock=document.getElementById('lock-view'),screen=document.getElementById('screen');
let minutes=720,manuals=0,opened=false,responded={},events=[],findingStates=[],reminded=false,ready=false,pendingOpen=false;
const clock=()=>`${String(Math.floor(minutes/60)).padStart(2,'0')}.${String(minutes%60).padStart(2,'0')}`;
const labels={water:'Tekanan air',socket:'Stopkontak',host:'Balasan tamu'};
function log(text){events.push({time:clock(),text});document.getElementById('announcement').textContent=text;}
function send(command){if(ready)frame.contentWindow.postMessage({source:'inspection-controller',command,time:clock(),minutes},location.origin);}
function needs(){return findingStates.length?findingStates.filter(f=>f.state==='needs').length:2;}
function notification(){const count=needs(),closed=findingStates.length&&findingStates.every(f=>f.state==='closed');let title,body;
 if(closed){title='Inspection selesai diverifikasi';body='Ketiga temuan sudah ditutup oleh tim BV. Ringkasan tindak lanjut tersedia di kasus yang sama.';}
 else if(!count){title='Respons Anda tercatat · Tim BV melanjutkan';body='Lihat jadwal, jawaban tim, dan verifikasi tiap temuan. Tidak ada permintaan respons owner yang masih tertunda.';}
 else if(minutes>750){title=`Tenggat terlewati · ${count} temuan belum direspons`;body='Villa Contoh: beri rencana pemeriksaan/perbaikan atau minta bantuan. Dina akan menindaklanjuti kasus ini.';}
 else if(opened){title=`${count} temuan masih menunggu respons`;body='Anda sudah membuka inspection. Pilih penanggung jawab dan target waktu, atau jelaskan jika Anda membutuhkan bantuan.';}
 else{title='Villa Contoh · Tanggapi inspection sebelum 12.30';body='Tentukan rencana untuk 2 temuan: tekanan air dan stopkontak. Satu temuan lainnya ditangani tim BV.';}
 lock.innerHTML=`<div class="clock-block"><div class="lock-symbol" aria-hidden="true">▣</div><div class="lock-date">Jumat, 2 Oktober</div><div class="lock-clock">${clock().replace('.',':')}</div><div class="lock-subtitle">${count?'Inspection membutuhkan tanggapan':'Pembaruan tindak lanjut'}</div></div><div class="notification-stack"><article class="notification-card"><div class="notification-header"><img src="bvgo-app-icon.png" alt="BVGO"><strong>BVGO</strong><time>sekarang</time></div><button class="notification-body" data-control="open"><div class="notif-title">${title}</div><p class="notif-copy">${body}</p><div class="notif-property">Privat · Villa Contoh</div></button><div class="notification-actions"><button data-control="open">${count?'Lihat temuan & tanggapi':'Lihat tindak lanjut'}</button></div></article><p class="app-notification-info">${count?'Batas respons: 2 Okt, 12.30 WITA.<br>Target perbaikan ditentukan terpisah.':closed?'Kasus ditutup setelah verifikasi tim BV.':'Respons owner sudah tercatat. Pantau tindak lanjut per temuan.'}</p></div>`;
}
function display(mode){const isLock=mode==='notification';lock.hidden=!isLock;frame.hidden=isLock;screen.classList.toggle('in-app',!isLock);document.getElementById('preview-label').textContent=isLock?'NOTIFIKASI BVGO':mode==='feed'?'FEED SWIPE · EXISTING':'INSPECTION · TINDAK LANJUT';if(isLock)notification();else if(ready)send(mode==='feed'?'feed':'open');else pendingOpen=mode;}
function update(){document.getElementById('sim-clock').textContent=clock()+' WITA';document.getElementById('status-time').textContent=clock();document.getElementById('manual-count').textContent=manuals;const responses=Object.values(responded);document.getElementById('response-count').textContent=responses.length+' / 2';const independent=responses.filter(r=>r.beforeManual).length,onTime=responses.every(r=>r.minutes<=750);
 document.getElementById('attribution').textContent=!responses.length?'Belum ada respons owner.':`${independent} respons sebelum follow-up manual; ${responses.length-independent} setelah follow-up manual. ${responses.length<2?'Kasus belum menerima seluruh respons.':onTime?(independent===2?'Kedua respons tepat waktu tanpa follow-up manual.':'Kedua respons tepat waktu, dengan bantuan follow-up manual.'):'Tidak semua respons masuk sebelum tenggat.'}`;
 const count=needs();document.getElementById('reminder-policy').textContent=findingStates.length&&findingStates.every(f=>f.state==='closed')?'Kasus selesai diverifikasi. Tidak ada pengingat atau pekerjaan tertunda.':count?`${count} temuan masih menunggu owner. ${opened?'Pengingat membuka dihentikan; pengingat hanya meminta respons yang belum ada.':'Notifikasi mengarah langsung ke kasus.'}${minutes>750?' Tenggat terlewati: perlu tindak lanjut PIC, tidak ditutup otomatis.':''}`:'Pengingat respons owner dihentikan. Pekerjaan terjadwal, permintaan bantuan, dan laporan selesai tetap ditindaklanjuti sesuai status masing-masing.';
 document.getElementById('bv-update').disabled=!findingStates.some(f=>['help','dispute'].includes(f.state));document.getElementById('verify').disabled=!findingStates.some(f=>f.state==='verify');document.getElementById('bv-complete').disabled=findingStates.some(f=>f.id==='host'&&f.state==='closed');
 const list=document.getElementById('event-log');list.replaceChildren();events.forEach(e=>{const li=document.createElement('li');li.textContent=`${e.time} · ${e.text}`;list.append(li);});if(!lock.hidden)notification();
}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.id==='reset'){minutes=720;manuals=0;opened=false;responded={};findingStates=[];events=[];reminded=false;ready=false;pendingOpen=false;frame.src='inspection-app.html?session='+Date.now();log('Sesi Action Feed dimulai');display('feed');update();return;}const c=b.dataset.control;if(['notification','feed','open'].includes(c)){display(c);return;}if(c==='manual'){manuals++;log('Follow-up telepon / WA manual dicatat (simulasi)');}if(c==='advance'){minutes=Math.min(1080,minutes+10);send('tick');if(minutes>=740&&needs()&&!reminded){reminded=true;log(opened?'Pengingat meminta respons untuk temuan yang tertunda':'Pengingat membuka dan merespons inspection');}else log('Waktu simulasi dimajukan');}if(['bv-update','verify','bv-complete'].includes(c))send(c);update();});
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==frame.contentWindow||e.data?.source!=='bvgo-inspection')return;const d=e.data;findingStates=d.findings;if(d.type==='ready'){ready=true;send('tick');if(pendingOpen){const mode=pendingOpen;pendingOpen=false;display(mode);}}
 if(d.type==='opened'){if(!opened){log('Owner membuka kasus inspection');opened=true;}}
 if(d.type==='response'){if(!responded[d.finding])responded[d.finding]={beforeManual:manuals===0,minutes};log(`Respons ${labels[d.finding]} tercatat: ${d.kind==='question'?'pertanyaan / sanggahan':d.kind==='plan'?'rencana tindak lanjut':'laporan pekerjaan selesai'}`);}
 if(d.type==='response_updated')log(`Rencana lanjutan ${labels[d.finding]} tercatat; respons awal tidak dihitung ulang`);
 if(d.type==='completion_reported')log(`Laporan penyelesaian ${labels[d.finding]} menunggu verifikasi BV`);
 if(d.type==='bv_update')log('Tim BV memberikan pembaruan pada permintaan bantuan / sanggahan');
 if(d.type==='verified')log(`${labels[d.finding]} diverifikasi selesai oleh BV (simulasi)`);
 if(d.type==='bv_completed')log('Tugas internal tim BV diverifikasi selesai (simulasi)');
 update();});
log('Sesi Action Feed dimulai');display('feed');update();
